# Generated by Django 5.2.11 on 2026-02-13 14:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('scan', 'QR Scan'), ('export', 'Data Export'), ('import', 'Data Import')], max_length=20, verbose_name='Action Type')),
                ('user', models.CharField(max_length=100, verbose_name='User')),
                ('description', models.TextField(verbose_name='Description')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Badge Name')),
                ('badge_type', models.CharField(choices=[('attendance', 'Attendance'), ('punctuality', 'Punctuality'), ('submission', 'Assignment Submission'), ('excellence', 'Excellence')], max_length=20, verbose_name='Type')),
                ('description', models.TextField(verbose_name='Description')),
                ('icon', models.CharField(default='🏆', max_length=50, verbose_name='Icon/Emoji')),
                ('points_required', models.IntegerField(default=0, verbose_name='Points Required')),
                ('color', models.CharField(default='gold', max_length=20, verbose_name='Color')),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Session Title')),
                ('session_type', models.CharField(choices=[('lecture', 'Lecture'), ('lab', 'Laboratory'), ('exam', 'Exam'), ('assignment', 'Assignment Submission'), ('other', 'Other')], default='lecture', max_length=20, verbose_name='Type')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Start Time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='End Time')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Location')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('geo_fence_radius', models.IntegerField(default=100, verbose_name='Geo-fence Radius (meters)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('university_id', models.CharField(max_length=50, unique=True, verbose_name='University ID')),
                ('name', models.CharField(max_length=200, verbose_name='Student Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR Code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_points', models.IntegerField(default=0, verbose_name='Total Points')),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Attendance %')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused'), ('submitted', 'Submitted')], default='present', max_length=20, verbose_name='Status')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Recorded At')),
                ('scan_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Scan Latitude')),
                ('scan_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Scan Longitude')),
                ('recorded_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Recorded By')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='students.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='students.student')),
            ],
            options={
                'verbose_name': 'Attendance Log',
                'verbose_name_plural': 'Attendance Logs',
                'ordering': ['-timestamp'],
                'unique_together': {('student', 'session')},
            },
        ),
        migrations.CreateModel(
            name='StudentBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True, verbose_name='Awarded At')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded_to', to='students.badge')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Badge',
                'verbose_name_plural': 'Student Badges',
                'ordering': ['-awarded_at'],
                'unique_together': {('student', 'badge')},
            },
        ),
    ]
